image: Visual Studio 2017

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1 -Target Test

# Tests
test: off

artifacts:
- path: buildArtifacts\Nuget\*.nupkg
  name: NuGet package
  
skip_commits:
  files:
    - '.github/'
    - '**/*.md'

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /feature/.*/
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:   
- tools -> build.cake

# here we are going to override common configuration
for:
# master branch
-
  branches:
    only:
      - master  
  build_script:
  - ps: .\build.ps1 -Target Pack
  deploy:
  - provider: NuGet
    artifact: /NuGet/
    api_key:
      secure: AkO5EDM5kiAVyhFhK/SKj7wUHHwNTP00gIk3pTvjKQETe08fGfdpFoJlqqL1DC7I